// 初期化時に画像リストをロード
export const imagePath = "img/";
export const imageList = [
  { fileName: "アイネスフウジン.png", altText: "(アイネス OR アイネスフウジン)" },
  { fileName: "アグネスタキオン.png", altText: "(タキオン OR アグネスタキオン)" },
  { fileName: "アグネスデジタル.png", altText: "(デジタル OR デジ OR アグネスデジタル)" },
  { fileName: "アストンマーチャン.png", altText: "(マーチャン OR アストンマーチャン)" },
  { fileName: "アドマイヤベガ.png", altText: "(アドべ OR アドマイヤベガ)" },
  { fileName: "イクノディクタス.png", altText: "(イクノ OR イクノディクタス)" },
  { fileName: "イナリワン.png", altText: "(イナリ OR イナリワン)" },
  { fileName: "ウイニングチケット.png", altText: "(チケット OR チケゾー OR ウイニングチケット)" },
  { fileName: "ウオッカ.png", altText: "(ウオッカ)" },
  { fileName: "エアグルーヴ.png", altText: "(女帝 OR エアグルーヴ)" },
  { fileName: "エアシャカール.png", altText: "(シャカール OR シャカ OR エアシャカール)" },
  { fileName: "エアメサイア.png", altText: "(エアメサイア)" },
  { fileName: "エイシンフラッシュ.png", altText: "(エイシンフラッシュ)" },
  { fileName: "エスポワールシチー.png", altText: "(エスポワールシチー)" },
  { fileName: "エルコンドルパサー.png", altText: "(エルコンドルパサー)" },
  { fileName: "オグリキャップ.png", altText: "(オグリキャップ)" },
  { fileName: "オルフェーヴル.png", altText: "(オルフェーヴル)" },
  { fileName: "カツラギエース.png", altText: "(カツラギエース)" },
  { fileName: "カルストンライトオ.png", altText: "(カルストンライトオ)" },
  { fileName: "カレンチャン.png", altText: "(カレンチャン)" },
  { fileName: "カワカミプリンセス.png", altText: "(カワカミ OR プリンセス OR カワカミプリンセス)" },
  { fileName: "キタサンブラック.png", altText: "(キタサン OR キタサンブラック)" },
  { fileName: "キングヘイロー.png", altText: "(キング OR キングヘイロー)" },
  { fileName: "グラスワンダー.png", altText: "(グラスワンダー)" },
  { fileName: "ケイエスミラクル.png", altText: "(ケイエスミラクル)" },
  { fileName: "コパノリッキー.png", altText: "(コパノリッキー)" },
  { fileName: "ゴールドシチー.png", altText: "(ゴールドシチー)" },
  { fileName: "ゴールドシップ.png", altText: "(ゴールドシップ)" },
  { fileName: "サイレンススズカ.png", altText: "(スズカ OR サイレンススズカ)" },
  { fileName: "サウンズオブアース.png", altText: "(サウンズオブアース)" },
  { fileName: "サクラチトセオー.png", altText: "(サクラチトセオー)" },
  { fileName: "サクラチヨノオー.png", altText: "(サクラチヨノオー)" },
  { fileName: "サクラバクシンオー.png", altText: "(サクラバクシンオー)" },
  { fileName: "サクラローレル.png", altText: "(サクラローレル)" },
  { fileName: "サトノクラウン.png", altText: "(サトノクラウン)" },
  { fileName: "サトノダイヤモンド.png", altText: "(サトノダイヤモンド)" },
  { fileName: "サムソンビッグ.png", altText: "(サムソンビッグ)" },
  { fileName: "シュヴァルグラン.png", altText: "(シュヴァルグラン)" },
  { fileName: "シリウスシンボリ.png", altText: "(シリウスシンボリ)" },
  { fileName: "シンコウウインディ.png", altText: "(シンコウウインディ)" },
  { fileName: "シンボリクリスエス.png", altText: "(シンボリクリスエス)" },
  { fileName: "シンボリルドルフ.png", altText: "(シンボリルドルフ)" },
  { fileName: "シーキングザパール.png", altText: "(シーキングザパール)" },
  { fileName: "シーザリオ.png", altText: "(シーザリオ)" },
  { fileName: "ジェンティルドンナ.png", altText: "(ジェンティルドンナ)" },
  { fileName: "ジャングルポケット.png", altText: "(ジャングルポケット)" },
  { fileName: "スイープトウショウ.png", altText: "(スイープトウショウ)" },
  { fileName: "スティルインラブ.png", altText: "(スティルインラブ)" },
  { fileName: "スペシャルウィーク.png", altText: "(スペシャルウィーク)" },
  { fileName: "スマートファルコン.png", altText: "(スマートファルコン)" },
  { fileName: "スーパークリーク.png", altText: "(スーパークリーク)" },
  { fileName: "セイウンスカイ.png", altText: "(セイウンスカイ)" },
  { fileName: "ゼンノロブロイ.png", altText: "(ゼンノロブロイ)" },
  { fileName: "タイキシャトル.png", altText: "(タイキシャトル)" },
  { fileName: "タップダンスシチー.png", altText: "(タップダンスシチー)" },
  { fileName: "タニノギムレット.png", altText: "(タニノギムレット)" },
  { fileName: "タマモクロス.png", altText: "(タマモクロス)" },
  { fileName: "ダイイチルビー.png", altText: "(ダイイチルビー)" },
  { fileName: "ダイタクヘリオス.png", altText: "(ダイタクヘリオス)" },
  { fileName: "ダイワスカーレット.png", altText: "(ダスカ OR スカーレット OR ダイワスカーレット)" },
  { fileName: "ダンツフレーム.png", altText: "(ダンツ OR ダンツフレーム)" },
  { fileName: "ツインターボ.png", altText: "(ターボ OR ツインターボ)" },
  { fileName: "ツルマルツヨシ.png", altText: "(ツルマルツヨシ)" },
  { fileName: "テイエムオペラオー.png", altText: "(テイエムオペラオー)" },
  { fileName: "デアリングタクト.png", altText: "(デアリングタクト)" },
  { fileName: "デアリングハート.png", altText: "(デアリングハート)" },
  { fileName: "デュランダル.png", altText: "(デュランダル)" },
  { fileName: "トウカイテイオー.png", altText: "(トウカイテイオー)" },
  { fileName: "トランセンド.png", altText: "(トランセンド)" },
  { fileName: "トーセンジョーダン.png", altText: "(トーセンジョーダン)" },
  { fileName: "ドゥラメンテ.png", altText: "(ドゥラメンテ)" },
  { fileName: "ドリームジャーニー.png", altText: "(ドリームジャーニー)" },
  { fileName: "ナイスネイチャ.png", altText: "(ネイチャ OR ナイスネイチャ)" },
  { fileName: "ナカヤマフェスタ.png", altText: "(ナカヤマフェスタ)" },
  { fileName: "ナリタタイシン.png", altText: "(ナリタタイシン)" },
  { fileName: "ナリタトップロード.png", altText: "(ナリタトップロード)" },
  { fileName: "ナリタブライアン.png", altText: "(ナリタブライアン)" },
  { fileName: "ニシノフラワー.png", altText: "(ニシノ OR フラワー OR ニシノフラワー)" },
  { fileName: "ネオユニヴァース.png", altText: "(ネオユニ OR ネオユニヴァース)" },
  { fileName: "ノースフライト.png", altText: "(ノースフライト)" },
  { fileName: "ノーリーズン.png", altText: "(ノーリーズン)" },
  { fileName: "ハッピーミーク.png", altText: "(ミーク OR ハッピーミーク)" },
  { fileName: "ハルウララ.png", altText: "(ウララ OR ハルウララ)" },
  { fileName: "バブルガムフェロー.png", altText: "(バブルガムフェロー)" },
  { fileName: "バンブーメモリー.png", altText: "(バンブー OR バンブーメモリー)" },
  { fileName: "ヒシアケボノ.png", altText: "(アケボノ OR ヒシアケボノ)" },
  { fileName: "ヒシアマゾン.png", altText: "(アマゾン OR ヒシアマ OR ヒシアマゾン)" },
  { fileName: "ヒシミラクル.png", altText: "(ヒシミラクル)" },
  { fileName: "ビコーペガサス.png", altText: "(ビコーペガサス)" },
  { fileName: "ビターグラッセ.png", altText: "(ビターグラッセ)" },
  { fileName: "ビリーヴ.png", altText: "(ビリーヴ)" },
  { fileName: "ビワハヤヒデ.png", altText: "(ビワハヤヒデ)" },
  { fileName: "ファインモーション.png", altText: "(殿下 OR 姫様 OR ファイン OR ファインモーション)" },
  { fileName: "フサイチパンドラ.png", altText: "(フサイチパンドラ)" },
  { fileName: "フジキセキ.png", altText: "(フジキセキ)" },
  { fileName: "フリオーソ.png", altText: "(フリオーソ)" },
  { fileName: "ブエナビスタ.png", altText: "(ブエナビスタ)" },
  { fileName: "ブラストワンピース.png", altText: "(ブラストワンピース)" },
  { fileName: "ホッコータルマエ.png", altText: "(ホッコータルマエ)" },
  { fileName: "マチカネタンホイザ.png", altText: "(マチカネタンホイザ)" },
  { fileName: "マチカネフクキタル.png", altText: "(マチカネフクキタル)" },
  { fileName: "マヤノトップガン.png", altText: "(マヤ OR マヤノ OR マヤノトップガン)" },
  { fileName: "マルゼンスキー.png", altText: "(マルゼンスキー)" },
  { fileName: "マンハッタンカフェ.png", altText: "(マンハッタンカフェ)" },
  { fileName: "マーベラスサンデー.png", altText: "(マーベラス OR マーベラスサンデー)" },
  { fileName: "ミスターシービー.png", altText: "(ミスターシービー)" },
  { fileName: "ミホノブルボン.png", altText: "(ミホノブルボン)" },
  { fileName: "メイショウドトウ.png", altText: "(メイショウドトウ)" },
  { fileName: "メジロアルダン.png", altText: "(メジロアルダン)" },
  { fileName: "メジロドーベル.png", altText: "(メジロドーベル)" },
  { fileName: "メジロパーマー.png", altText: "(メジロパーマー)" },
  { fileName: "メジロブライト.png", altText: "(メジロブライト)" },
  { fileName: "メジロマックイーン.png", altText: "(メジロマックイーン)" },
  { fileName: "メジロライアン.png", altText: "(メジロライアン)" },
  { fileName: "メジロラモーヌ.png", altText: "(メジロラモーヌ)" },
  { fileName: "ヤエノムテキ.png", altText: "(ヤエノムテキ)" },
  { fileName: "ヤマニンゼファー.png", altText: "(ヤマニンゼファー)" },
  { fileName: "ユキノビジン.png", altText: "(ユキノビジン)" },
  { fileName: "ライスシャワー.png", altText: "(ライスシャワー)" },
  { fileName: "ラインクラフト.png", altText: "(ラインクラフト)" },
  { fileName: "リガントーナ.png", altText: "(リガントーナ)" },
  { fileName: "リトルココン.png", altText: "(リトルココン)" },
  { fileName: "ロイスアンドロイス.png", altText: "(ロイスアンドロイス)" },
  { fileName: "ワンダーアキュート.png", altText: "(ワンダーアキュート)" },
  { fileName: "ヴィブロス.png", altText: "(ヴィブロス)" },
  { fileName: "ヴィルシーナ.png", altText: "(ヴィルシーナ)" },
  { fileName: "ヴェニュスパーク.png", altText: "(ヴェニュスパーク)" },
  { fileName: "ゴドルフィンバルブ.png", altText: "(ゴドルフィンバルブ)" },
  { fileName: "ダーレーアラビアン.png", altText: "(ダーレーアラビアン)" },
  { fileName: "バイアリーターク.png", altText: "(バイアリーターク)" },
  { fileName: "シュガーライツ.png", altText: "(博士 OR ライツ OR シュガーライツ)" },
  { fileName: "ソノンエルフィー.png", altText: "(ソノンエルフィー)" },
  { fileName: "ライトハロー.png", altText: "(ハロー OR ライトハロー)" },
  { fileName: "乙名史悦子.png", altText: "(乙名史悦子)" },
  { fileName: "佐岳メイ.png", altText: "(佐岳 OR メイ OR 佐岳メイ)" },
  { fileName: "安心沢刺々美.png", altText: "(安心沢 OR 不審者 OR 安心沢刺々美)" },
  { fileName: "桐生院葵.png", altText: "(鬼龍院 OR 桐生院 OR 葵 OR 桐生院葵)" },
  { fileName: "樫本理子.png", altText: "(理子 OR 樫本理子)" },
  { fileName: "秋川やよい.png", altText: "(やよい OR 秋川やよい)" },
  { fileName: "都留岐涼花.png", altText: "(都留岐涼花)" },
  { fileName: "駿川たづな.png", altText: "(トキノミノル OR たづな OR 駿川たづな)" },
  { fileName: "沖野トレーナー.png", altText: "(沖野トレーナー)" },
  { fileName: "黒沼トレーナー.png", altText: "(黒沼トレーナー)" },
  { fileName: "東条ハナトレーナー.png", altText: "(東条ハナトレーナー)" },
  { fileName: "南坂トレーナー.png", altText: "(南坂トレーナー)" },
  { fileName: "女トレーナー.png", altText: "(トレーナー OR 女トレ OR 女トレーナー)" },
  { fileName: "男トレーナー.png", altText: "(トレーナー OR 男トレ OR 男トレーナー)" },
  // 他の画像ファイルもここにリストアップ
];
