// 初期化時に画像リストをロード
export const imagePath = "img_webp/";
export const imageList = [
  { fileName: "アイネスフウジン_70.webp", altText: "(アイネス OR アイネスフウジン)" },
  { fileName: "アグネスタキオン_70.webp", altText: "(タキオン OR アグネスタキオン)" },
  { fileName: "アグネスデジタル_70.webp", altText: "(デジタル OR デジ OR アグネスデジタル)" },
  { fileName: "アストンマーチャン_70.webp", altText: "(マーチャン OR アストンマーチャン)" },
  { fileName: "アドマイヤグルーヴ_70.webp", altText: "(アドマイヤグルーヴ OR アルヴ)" },
  { fileName: "アドマイヤベガ_70.webp", altText: "(アヤベ OR アドべ OR アドマイヤベガ)" },
  { fileName: "アーモンドアイ_70.webp", altText: "(アーモンドアイ)" },
  { fileName: "イクノディクタス_70.webp", altText: "(イクノ OR イクノディクタス)" },
  { fileName: "イナリワン_70.webp", altText: "(イナリ OR イナリワン)" },
  { fileName: "ウイニングチケット_70.webp", altText: "(チケット OR チケゾー OR ウイニングチケット)" },
  { fileName: "ヴィブロス_70.webp", altText: "(ヴィブロス)" },
  { fileName: "ヴィルシーナ_70.webp", altText: "(ヴィルシーナ)" },
  { fileName: "ウインバリアシオン_70.webp", altText: "(シオン OR バリちゃん OR ウインバリアシオン)" },
  { fileName: "ヴェニュスパーク_70.webp", altText: "(ヴェニュスパーク)" },
  { fileName: "ウオッカ_70.webp", altText: "(ウォッカ OR ウオッカ)" },
  { fileName: "エアグルーヴ_70.webp", altText: "(女帝 OR エアグルーヴ)" },
  { fileName: "エアシャカール_70.webp", altText: "(シャカール OR シャカ OR エアシャカール)" },
  { fileName: "エアメサイア_70.webp", altText: "(メサイア OR エアメサイア)" },
  { fileName: "エイシンフラッシュ_70.webp", altText: "(フラッシュ OR エイシンフラッシュ)" },
  { fileName: "エスポワールシチー_70.webp", altText: "(エスポ OR エスポワールシチー)" },
  { fileName: "エルコンドルパサー_70.webp", altText: "(エル OR エルコンドルパサー)" },
  { fileName: "オグリキャップ_70.webp", altText: "(オグリ OR オグリキャップ)" },
  { fileName: "オルフェーヴル_70.webp", altText: "(オル OR オルフェ OR オルフェーヴル)" },
  { fileName: "カツラギエース_70.webp", altText: "(エース OR カツラギエース)" },
  { fileName: "カルストンライトオ_70.webp", altText: "(カルストンライトオ)" },
  { fileName: "カレンチャン_70.webp", altText: "(カレン OR カレンチャン)" },
  { fileName: "カレンブーケドール_70.webp", altText: "(カレンブーケドール)" },
  { fileName: "カワカミプリンセス_70.webp", altText: "(カワカミ OR プリンセス OR カワカミプリンセス)" },
  { fileName: "キセキ_70.webp", altText: "(キセキ)" },
  { fileName: "キタサンブラック_70.webp", altText: "(キタサン OR キタサンブラック)" },
  { fileName: "キングヘイロー_70.webp", altText: "(キング OR キングヘイロー)" },
  { fileName: "クロノジェネシス_70.webp", altText: "(クロノジェネシス)" },
  { fileName: "グラスワンダー_70.webp", altText: "(グラス OR グラスワンダー)" },
  { fileName: "グランアレグリア_70.webp", altText: "(グランアレグリア)" },
  { fileName: "ケイエスミラクル_70.webp", altText: "(ケイ OR ケイエス OR ケイエスミラクル)" },
  { fileName: "ゴールドシチー_70.webp", altText: "(シチー OR ゴールドシチー)" },
  { fileName: "ゴールドシップ_70.webp", altText: "(ゴルシ OR ゴールドシップ)" },
  { fileName: "コパノリッキー_70.webp", altText: "(コパ OR リッキー OR コパノリッキー)" },
  { fileName: "サイレンススズカ_70.webp", altText: "(スズカ OR サイレンススズカ)" },
  { fileName: "サウンズオブアース_70.webp", altText: "(アース OR サウンズオブアース)" },
  { fileName: "サクラチトセオー_70.webp", altText: "(チトセ OR サクラチトセオー)" },
  { fileName: "サクラチヨノオー_70.webp", altText: "(チヨ OR サクラチヨノオー)" },
  { fileName: "サクラバクシンオー_70.webp", altText: "(バクシン OR サクラバクシンオー)" },
  { fileName: "サクラローレル_70.webp", altText: "(ローレル OR サクラローレル)" },
  { fileName: "サトノクラウン_70.webp", altText: "(クラ OR サトノクラウン)" },
  { fileName: "サトノダイヤモンド_70.webp", altText: "(ダイヤ OR サトノダイヤモンド)" },
  { fileName: "サムソンビッグ_70.webp", altText: "(サムソンビッグ)" },
  { fileName: "シーキングザパール_70.webp", altText: "(パール OR ザパ OR シーキングザパール)" },
  { fileName: "シーザリオ_70.webp", altText: "(ザリオ OR シーザリオ)" },
  { fileName: "ジェンティルドンナ_70.webp", altText: "(ジェンティル OR ドンナ OR ジェンティルドンナ)" },
  { fileName: "ジャングルポケット_70.webp", altText: "(ポッケ OR ポケット OR ジャングルポケット)" },
  { fileName: "シュヴァルグラン_70.webp", altText: "(シュヴァ OR シュヴァルグラン)" },
  { fileName: "シリウスシンボリ_70.webp", altText: "(シリウス OR シリウスシンボリ)" },
  { fileName: "シンコウウインディ_70.webp", altText: "(ウインディ OR シンコウウインディ)" },
  { fileName: "シンボリクリスエス_70.webp", altText: "(クリスエス OR シンボリクリスエス)" },
  { fileName: "シンボリルドルフ_70.webp", altText: "(会長 OR ルドルフ OR ｶｲﾁｮ OR シンボリルドルフ)" },
  { fileName: "スイープトウショウ_70.webp", altText: "(スイープ OR スイープトウショウ)" },
  { fileName: "スーパークリーク_70.webp", altText: "(クリーク OR スーパークリーク)" },
  { fileName: "ステイゴールド_70.webp", altText: "(ステゴ OR ステイゴールド)" },
  { fileName: "スティルインラブ_70.webp", altText: "(スティル OR スティルインラブ)" },
  { fileName: "スピードシンボリ_70.webp", altText: "(スピードシンボリ)" },
  { fileName: "スペシャルウィーク_70.webp", altText: "(スペ OR 日本総大将 OR スペシャルウィーク)" },
  { fileName: "スマートファルコン_70.webp", altText: "(ウマドル OR ファルコ OR スマートファルコン)" },
  { fileName: "セイウンスカイ_70.webp", altText: "(ウンス OR スカイ OR セイウンスカイ)" },
  { fileName: "セントライト_70.webp", altText: "(セントライト)" },
  { fileName: "ゼンノロブロイ_70.webp", altText: "(ロブロイ OR ゼンノロブロイ)" },
  { fileName: "ダイイチルビー_70.webp", altText: "(ルビー OR お嬢 OR ダイイチルビー)" },
  { fileName: "タイキシャトル_70.webp", altText: "(タイキ OR タイキシャトル)" },
  { fileName: "ダイタクヘリオス_70.webp", altText: "(ヘリオス OR ダイタクヘリオス)" },
  { fileName: "ダイワスカーレット_70.webp", altText: "(ダスカ OR スカーレット OR ダイワスカーレット)" },
  { fileName: "タップダンスシチー_70.webp", altText: "(タップ OR タップダンスシチー)" },
  { fileName: "タニノギムレット_70.webp", altText: "(ギム OR タニノギムレット)" },
  { fileName: "タマモクロス_70.webp", altText: "(タマ OR タマモ OR タマモクロス)" },
  { fileName: "ダンツフレーム_70.webp", altText: "(ダンツ OR ダンツフレーム)" },
  { fileName: "ツインターボ_70.webp", altText: "(ターボ OR ツインターボ)" },
  { fileName: "ツルマルツヨシ_70.webp", altText: "(ツヨシ OR ツルマルツヨシ)" },
  { fileName: "デアリングタクト_70.webp", altText: "(タクト OR デアリングタクト)" },
  { fileName: "デアリングハート_70.webp", altText: "(デアリングハート)" },
  { fileName: "テイエムオペラオー_70.webp", altText: "(オペラオー OR テイエムオペラオー)" },
  { fileName: "デュランダル_70.webp", altText: "(デュランダル)" },
  { fileName: "トウカイテイオー_70.webp", altText: "(テイオー OR ﾓﾝﾆ OR トウカイテイオー)" },
  { fileName: "ドゥラメンテ_70.webp", altText: "(ドゥラ OR ドゥラメンテ)" },
  { fileName: "トーセンジョーダン_70.webp", altText: "(ジョーダン OR トーセンジョーダン)" },
  { fileName: "トランセンド_70.webp", altText: "(トランセンド)" },
  { fileName: "ドリームジャーニー_70.webp", altText: "(ドリジャ OR 姉上 OR ジャーニーOR ドリームジャーニー)" },
  { fileName: "ナイスネイチャ_70.webp", altText: "(ネイチャ OR ナイスネイチャ)" },
  { fileName: "ナカヤマフェスタ_70.webp", altText: "(ナカヤマ OR フェスタ OR ナカヤマフェスタ)" },
  { fileName: "ナリタタイシン_70.webp", altText: "(タイシン OR ナリタタイシン)" },
  { fileName: "ナリタトップロード_70.webp", altText: "(NTR OR トプロ OR ナリタトップロード)" },
  { fileName: "ナリタブライアン_70.webp", altText: "(ナリブ OR ブライアン OR ナリタブライアン)" },
  { fileName: "ニシノフラワー_70.webp", altText: "(ニシノ OR フラワー OR ニシノフラワー)" },
  { fileName: "ネオユニヴァース_70.webp", altText: "(ネオユニ OR ネオユニヴァース)" },
  { fileName: "ノースフライト_70.webp", altText: "(ノースフライト)" },
  { fileName: "ノーリーズン_70.webp", altText: "(ズン子 OR ノーリーズン)" },
  { fileName: "ハイセイコー_70.webp", altText: "(ハイセイコー)" },
  { fileName: "ハッピーミーク_70.webp", altText: "(ミーク OR ハッピーミーク)" },
  { fileName: "バブルガムフェロー_70.webp", altText: "(バブルガムフェロー)" },
  { fileName: "ハルウララ_70.webp", altText: "(ウララ OR ハルウララ)" },
  { fileName: "バンブーメモリー_70.webp", altText: "(バンちゃむ OR バンブー OR バンブーメモリー)" },
  { fileName: "ビコーペガサス_70.webp", altText: "(ビコー OR ビコペ OR ビコーペガサス)" },
  { fileName: "ヒシアケボノ_70.webp", altText: "(ボーノ OR アケボノ OR ヒシアケボノ)" },
  { fileName: "ヒシアマゾン_70.webp", altText: "(アマゾン OR ヒシアマ OR ヒシアマゾン)" },
  { fileName: "ヒシミラクル_70.webp", altText: "(ミラ子 OR ヒシミラクル)" },
  { fileName: "ビターグラッセ_70.webp", altText: "(グラッセ OR ビターグラッセ)" },
  { fileName: "ビリーヴ_70.webp", altText: "(ビリーヴ)" },
  { fileName: "ビワハヤヒデ_70.webp", altText: "(姉貴 OR ハヤヒデ OR ビワハヤヒデ)" },
  { fileName: "ファインモーション_70.webp", altText: "(殿下 OR 姫様 OR ファイン OR ファインモーション)" },
  { fileName: "フェノーメノ_70.webp", altText: "(フェノーメノ)" },
  { fileName: "ブエナビスタ_70.webp", altText: "(ブエナビスタ)" },
  { fileName: "フサイチパンドラ_70.webp", altText: "(パンドラ OR フサイチパンドラ)" },
  { fileName: "フジキセキ_70.webp", altText: "(寮長 OR フジ OR キセキ OR フジキセキ)" },
  { fileName: "ブラストワンピース_70.webp", altText: "(ブラストワンピース)" },
  { fileName: "フリオーソ_70.webp", altText: "(フリオ OR フリオーソ)" },
  { fileName: "ホッコータルマエ_70.webp", altText: "(タルマエ OR ロコドル OR ホッコータルマエ)" },
  { fileName: "マーベラスサンデー_70.webp", altText: "(マーベラス OR マーベラスサンデー)" },
  { fileName: "マチカネタンホイザ_70.webp", altText: "(タンホイザ OR おマチさん OR マチタン OR マチカネタンホイザ)" },
  { fileName: "マチカネフクキタル_70.webp", altText: "(ﾌﾝｷﾞｬﾛ OR フクキタル OR マチカネフクキタル)" },
  { fileName: "マヤノトップガン_70.webp", altText: "(マヤ OR マヤノ OR マヤノトップガン)" },
  { fileName: "マルゼンスキー_70.webp", altText: "(マブ OR マルゼン OR マルゼンスキー)" },
  { fileName: "マンハッタンカフェ_70.webp", altText: "(カフェ OR マンハッタンカフェ)" },
  { fileName: "ミスターシービー_70.webp", altText: "(シービー OR CB OR ミスターシービー)" },
  { fileName: "ミホノブルボン_70.webp", altText: "(ブルボン OR ミホノブルボン)" },
  { fileName: "メイショウドトウ_70.webp", altText: "(ドトウ OR メイショウドトウ)" },
  { fileName: "メジロアルダン_70.webp", altText: "(アルダン OR メジロアルダン)" },
  { fileName: "メジロドーベル_70.webp", altText: "(ドーベル OR どぼめ OR メジロドーベル)" },
  { fileName: "メジロパーマー_70.webp", altText: "(パーマー OR パマちん OR メジロパーマー)" },
  { fileName: "メジロブライト_70.webp", altText: "(ブライト OR メジロブライト)" },
  { fileName: "メジロマックイーン_70.webp", altText: "(マックイーン OR メジロマックイーン)" },
  { fileName: "メジロライアン_70.webp", altText: "(ライアン OR メジロライアン)" },
  { fileName: "メジロラモーヌ_70.webp", altText: "(ラモーヌ OR メジロラモーヌ)" },
  { fileName: "ヤエノムテキ_70.webp", altText: "(ヤエノ OR ヤエめろ OR ヤエノムテキ)" },
  { fileName: "ヤマニンゼファー_70.webp", altText: "(ゼファー OR ヤマニンゼファー)" },
  { fileName: "ユキノビジン_70.webp", altText: "(ユキノ OR ユキノビジン)" },
  { fileName: "ユノハナブルーム_70.webp", altText: "(ユノハナブルーム OR ユノハナ OR ブルーム)" },
  { fileName: "ライスシャワー_70.webp", altText: "(ライス OR ライスシャワー)" },
  { fileName: "ラインクラフト_70.webp", altText: "(ラインクラフト)" },
  { fileName: "ラッキーライラック_70.webp", altText: "(ラッキーライラック)" },
  { fileName: "ラヴズオンリーユー_70.webp", altText: "(ラヴズオンリーユー)" },
  { fileName: "リガントーナ_70.webp", altText: "(リガントーナ)" },
  { fileName: "リトルココン_70.webp", altText: "(リトルココン)" },
  { fileName: "レッドディザイア_70.webp", altText: "(レッドディザイア OR ディザイア OR デザイア)" },
  { fileName: "ロイスアンドロイス_70.webp", altText: "(ロイス OR ロイスアンドロイス)" },
  { fileName: "ワンダーアキュート_70.webp", altText: "(アキュート OR ワンダーアキュート)" },
  { fileName: "ゴドルフィンバルブ_70.webp", altText: "(ゴドルフィンバルブ)" },
  { fileName: "ダーレーアラビアン_70.webp", altText: "(ダーレーアラビアン)" },
  { fileName: "バイアリーターク_70.webp", altText: "(バイアリーターク)" },
  { fileName: "シュガーライツ_70.webp", altText: "(博士 OR シュガー OR ライツ OR シュガーライツ)" },
  { fileName: "ソノンエルフィー_70.webp", altText: "(エルフィー OR ソノンエルフィー)" },
  { fileName: "ライトハロー_70.webp", altText: "(ハロー OR ライトハロー)" },
  { fileName: "タッカーブライン_70.webp", altText: "(タッカー OR ブライン OR タッカーブライン)" },
  { fileName: "乙名史悦子_70.webp", altText: "(悦子 OR 乙名史 OR 乙名史悦子)" },
  { fileName: "佐岳メイ_70.webp", altText: "(佐岳 OR メイ OR 佐岳メイ)" },
  { fileName: "安心沢刺々美_70.webp", altText: "(安心沢 OR 不審者 OR 安心沢刺々美)" },
  { fileName: "桐生院葵_70.webp", altText: "(鬼龍院 OR 桐生院 OR 葵 OR 桐生院葵)" },
  { fileName: "保科健子_70.webp", altText: "(保科健子 OR 保科 OR 女将)" },
  { fileName: "樫本理子_70.webp", altText: "(理子 OR 樫本理子)" },
  { fileName: "秋川やよい_70.webp", altText: "(やよい OR 秋川やよい)" },
  { fileName: "都留岐涼花_70.webp", altText: "(都留岐 OR 涼花 OR 都留岐涼花)" },
  { fileName: "駿川たづな_70.webp", altText: "(トキノミノル OR たづな OR 駿川たづな)" },
  { fileName: "沖野トレーナー_70.webp", altText: "(沖野トレーナー)" },
  { fileName: "黒沼トレーナー_70.webp", altText: "(黒沼トレーナー)" },
  { fileName: "東条ハナトレーナー_70.webp", altText: "(東条ハナトレーナー)" },
  { fileName: "南坂トレーナー_70.webp", altText: "(南坂トレーナー)" },
  { fileName: "女トレーナー_70.webp", altText: "(トレーナー OR 女トレ OR 女トレーナー)" },
  { fileName: "男トレーナー_70.webp", altText: "(トレーナー OR 男トレ OR 男トレーナー)" },
  // 他の画像ファイルもここにリストアップ
];
